SUPPORTED_LANGUAGES = [   
    {'label': 'Afar', 'value': 'aa'},
    {'label': 'Abkhazian', 'value': 'ab'},
    {'label': 'Afrikaans', 'value': 'af'},
    {'label': 'Akan', 'value': 'ak'},
    {'label': 'Amharic', 'value': 'am'},
    {'label': 'Arabic', 'value': 'ar'},
    {'label': 'Aragonese', 'value': 'an'},
    {'label': 'Assamese', 'value': 'as'},
    {'label': 'Avaric', 'value': 'av'},
    {'label': 'Avestan', 'value': 'ae'},
    {'label': 'Aymara', 'value': 'ay'},
    {'label': 'Azerbaijani', 'value': 'az'},
    {'label': 'Bashkir', 'value': 'ba'},
    {'label': 'Bambara', 'value': 'bm'},
    {'label': 'Belarusian', 'value': 'be'},
    {'label': 'Bengali', 'value': 'bn'},
    {'label': 'Bislama', 'value': 'bi'},
    {'label': 'Tibetan', 'value': 'bo'},
    {'label': 'Bosnian', 'value': 'bs'},
    {'label': 'Breton', 'value': 'br'},
    {'label': 'Bulgarian', 'value': 'bg'},
    {'label': 'Catalan', 'value': 'ca'},
    {'label': 'Czech', 'value': 'cs'},
    {'label': 'Chamorro', 'value': 'ch'},
    {'label': 'Chechen', 'value': 'ce'},
    {'label': 'Church Slavic', 'value': 'cu'},
    {'label': 'Chuvash', 'value': 'cv'},
    {'label': 'Cornish', 'value': 'kw'},
    {'label': 'Corsican', 'value': 'co'},
    {'label': 'Cree', 'value': 'cr'},
    {'label': 'Welsh', 'value': 'cy'},
    {'label': 'Danish', 'value': 'da'},
    {'label': 'German', 'value': 'de'},
    {'label': 'Dhivehi', 'value': 'dv'},
    {'label': 'Dzongkha', 'value': 'dz'},
    {'label': 'Modern Greek (1453-)', 'value': 'el'},
    {'label': 'English', 'value': 'en'},
    {'label': 'Esperanto', 'value': 'eo'},
    {'label': 'Estonian', 'value': 'et'},
    {'label': 'Basque', 'value': 'eu'},
    {'label': 'Ewe', 'value': 'ee'},
    {'label': 'Faroese', 'value': 'fo'},
    {'label': 'Persian', 'value': 'fa'},
    {'label': 'Fijian', 'value': 'fj'},
    {'label': 'Finnish', 'value': 'fi'},
    {'label': 'French', 'value': 'fr'},
    {'label': 'Western Frisian', 'value': 'fy'},
    {'label': 'Fulah', 'value': 'ff'},
    {'label': 'Scottish Gaelic', 'value': 'gd'},
    {'label': 'Irish', 'value': 'ga'},
    {'label': 'Galician', 'value': 'gl'},
    {'label': 'Manx', 'value': 'gv'},
    {'label': 'Guarani', 'value': 'gn'},
    {'label': 'Gujarati', 'value': 'gu'},
    {'label': 'Haitian', 'value': 'ht'},
    {'label': 'Hausa', 'value': 'ha'},
    {'label': 'Serbo-Croatian', 'value': 'sh'},
    {'label': 'Hebrew', 'value': 'he'},
    {'label': 'Herero', 'value': 'hz'},
    {'label': 'Hindi', 'value': 'hi'},
    {'label': 'Hiri Motu', 'value': 'ho'},
    {'label': 'Croatian', 'value': 'hr'},
    {'label': 'Hungarian', 'value': 'hu'},
    {'label': 'Armenian', 'value': 'hy'},
    {'label': 'Igbo', 'value': 'ig'},
    {'label': 'Ido', 'value': 'io'},
    {'label': 'Sichuan Yi', 'value': 'ii'},
    {'label': 'Inuktitut', 'value': 'iu'},
    {'label': 'Interlingue', 'value': 'ie'},
    {'label': 'Interlingua (International Auxiliary Language Association)',
    'value': 'ia'},
    {'label': 'Indonesian', 'value': 'id'},
    {'label': 'Inupiaq', 'value': 'ik'},
    {'label': 'Icelandic', 'value': 'is'},
    {'label': 'Italian', 'value': 'it'},
    {'label': 'Javanese', 'value': 'jv'},
    {'label': 'Japanese', 'value': 'ja'},
    {'label': 'Kalaallisut', 'value': 'kl'},
    {'label': 'Kannada', 'value': 'kn'},
    {'label': 'Kashmiri', 'value': 'ks'},
    {'label': 'Georgian', 'value': 'ka'},
    {'label': 'Kanuri', 'value': 'kr'},
    {'label': 'Kazakh', 'value': 'kk'},
    {'label': 'Khmer', 'value': 'km'},
    {'label': 'Kikuyu', 'value': 'ki'},
    {'label': 'Kinyarwanda', 'value': 'rw'},
    {'label': 'Kirghiz', 'value': 'ky'},
    {'label': 'Komi', 'value': 'kv'},
    {'label': 'Kongo', 'value': 'kg'},
    {'label': 'Korean', 'value': 'ko'},
    {'label': 'Kuanyama', 'value': 'kj'},
    {'label': 'Kurdish', 'value': 'ku'},
    {'label': 'Lao', 'value': 'lo'},
    {'label': 'Latin', 'value': 'la'},
    {'label': 'Latvian', 'value': 'lv'},
    {'label': 'Limburgan', 'value': 'li'},
    {'label': 'Lingala', 'value': 'ln'},
    {'label': 'Lithuanian', 'value': 'lt'},
    {'label': 'Luxembourgish', 'value': 'lb'},
    {'label': 'Luba-Katanga', 'value': 'lu'},
    {'label': 'Ganda', 'value': 'lg'},
    {'label': 'Marshallese', 'value': 'mh'},
    {'label': 'Malayalam', 'value': 'ml'},
    {'label': 'Marathi', 'value': 'mr'},
    {'label': 'Macedonian', 'value': 'mk'},
    {'label': 'Malagasy', 'value': 'mg'},
    {'label': 'Maltese', 'value': 'mt'},
    {'label': 'Mongolian', 'value': 'mn'},
    {'label': 'Maori', 'value': 'mi'},
    {'label': 'Malay (macrolanguage)', 'value': 'ms'},
    {'label': 'Burmese', 'value': 'my'},
    {'label': 'Nauru', 'value': 'na'},
    {'label': 'Navajo', 'value': 'nv'},
    {'label': 'South Ndebele', 'value': 'nr'},
    {'label': 'North Ndebele', 'value': 'nd'},
    {'label': 'Ndonga', 'value': 'ng'},
    {'label': 'Nepali (macrolanguage)', 'value': 'ne'},
    {'label': 'Dutch', 'value': 'nl'},
    {'label': 'Norwegian Nynorsk', 'value': 'nn'},
    {'label': 'Norwegian Bokmål', 'value': 'nb'},
    {'label': 'Norwegian', 'value': 'no'},
    {'label': 'Nyanja', 'value': 'ny'},
    {'label': 'Occitan (post 1500)', 'value': 'oc'},
    {'label': 'Ojibwa', 'value': 'oj'},
    {'label': 'Oriya (macrolanguage)', 'value': 'or'},
    {'label': 'Oromo', 'value': 'om'},
    {'label': 'Ossetian', 'value': 'os'},
    {'label': 'Panjabi', 'value': 'pa'},
    {'label': 'Pali', 'value': 'pi'},
    {'label': 'Polish', 'value': 'pl'},
    {'label': 'Portuguese', 'value': 'pt'},
    {'label': 'Pushto', 'value': 'ps'},
    {'label': 'Quechua', 'value': 'qu'},
    {'label': 'Romansh', 'value': 'rm'},
    {'label': 'Romanian', 'value': 'ro'},
    {'label': 'Rundi', 'value': 'rn'},
    {'label': 'Russian', 'value': 'ru'},
    {'label': 'Sango', 'value': 'sg'},
    {'label': 'Sanskrit', 'value': 'sa'},
    {'label': 'Sinhala', 'value': 'si'},
    {'label': 'Slovak', 'value': 'sk'},
    {'label': 'Slovenian', 'value': 'sl'},
    {'label': 'Northern Sami', 'value': 'se'},
    {'label': 'Samoan', 'value': 'sm'},
    {'label': 'Shona', 'value': 'sn'},
    {'label': 'Sindhi', 'value': 'sd'},
    {'label': 'Somali', 'value': 'so'},
    {'label': 'Southern Sotho', 'value': 'st'},
    {'label': 'Spanish', 'value': 'es'},
    {'label': 'Albanian', 'value': 'sq'},
    {'label': 'Sardinian', 'value': 'sc'},
    {'label': 'Serbian', 'value': 'sr'},
    {'label': 'Swati', 'value': 'ss'},
    {'label': 'Sundanese', 'value': 'su'},
    {'label': 'Swahili (macrolanguage)', 'value': 'sw'},
    {'label': 'Swedish', 'value': 'sv'},
    {'label': 'Tahitian', 'value': 'ty'},
    {'label': 'Tamil', 'value': 'ta'},
    {'label': 'Tatar', 'value': 'tt'},
    {'label': 'Telugu', 'value': 'te'},
    {'label': 'Tajik', 'value': 'tg'},
    {'label': 'Tagalog', 'value': 'tl'},
    {'label': 'Thai', 'value': 'th'},
    {'label': 'Tigrinya', 'value': 'ti'},
    {'label': 'Tonga (Tonga Islands)', 'value': 'to'},
    {'label': 'Tswana', 'value': 'tn'},
    {'label': 'Tsonga', 'value': 'ts'},
    {'label': 'Turkmen', 'value': 'tk'},
    {'label': 'Turkish', 'value': 'tr'},
    {'label': 'Twi', 'value': 'tw'},
    {'label': 'Uighur', 'value': 'ug'},
    {'label': 'Ukrainian', 'value': 'uk'},
    {'label': 'Urdu', 'value': 'ur'},
    {'label': 'Uzbek', 'value': 'uz'},
    {'label': 'Venda', 'value': 've'},
    {'label': 'Vietnamese', 'value': 'vi'},
    {'label': 'Volapük', 'value': 'vo'},
    {'label': 'Walloon', 'value': 'wa'},
    {'label': 'Wolof', 'value': 'wo'},
    {'label': 'Xhosa', 'value': 'xh'},
    {'label': 'Yiddish', 'value': 'yi'},
    {'label': 'Yoruba', 'value': 'yo'},
    {'label': 'Zhuang', 'value': 'za'},
    {'label': 'Chinese', 'value': 'zh'},
    {'label': 'Zulu', 'value': 'zu'},
    {'label': 'Ancient Greek', 'value': 'grc'}
    ]