MODEL_CONFIFURATIONS = {
    "word2vec": {
        "id": "word2vec",
        "family": "Word2Vec",
        "language_list": ['en','grc', 'ar', 'eu', 'bg', 'ca', 'zh', 'hr', 'cs', 'da', 'nl', 'et', 'fi', 'fr', 'gl', 'de', 'el', 'he', 'hi', 'hu', 'id', 'ga', 'it', 'ja', 'kk', 'ko', 'la', 'lv', 'nb', 'nn', 'cu', 'fa', 'pl', 'pt', 'ro', 'ru', 'sk', 'sl', 'es', 'sv', 'tr', 'uk', 'ur', 'ug', 'vi'],
        "download_info": {
            "en": {
                "model_link": "https://docs.google.com/uc?export=download",
                "id_gdrive": "0B7XkCwpI5KDYNlNUTTlSS21pQmM"
            },
            'grc': {'model_id': 30},
            'ar': {'model_id': 31},
            'eu': {'model_id': 32},
            'bg': {'model_id': 33},
            'ca': {'model_id': 34},
            'zh': {'model_id': 35},
            'hr': {'model_id': 36},
            'cs': {'model_id': 37},
            'da': {'model_id': 38},
            'nl': {'model_id': 39},
            'et': {'model_id': 41},
            'fi': {'model_id': 42},
            'fr': {'model_id': 43},
            'gl': {'model_id': 44},
            'de': {'model_id': 45},
            'el': {'model_id': 46},
            'he': {'model_id': 47},
            'hi': {'model_id': 48},
            'hu': {'model_id': 49},
            'id': {'model_id': 50},
            'ga': {'model_id': 51},
            'it': {'model_id': 52},
            'ja': {'model_id': 53},
            'kk': {'model_id': 54},
            'ko': {'model_id': 55},
            'la': {'model_id': 56},
            'lv': {'model_id': 57},
            'nb': {'model_id': 58},
            'nn': {'model_id': 59},
            'cu': {'model_id': 60},
            'fa': {'model_id': 61},
            'pl': {'model_id': 62},
            'pt': {'model_id': 63},
            'ro': {'model_id': 64},
            'ru': {'model_id': 65},
            'sk': {'model_id': 66},
            'sl': {'model_id': 67},
            'es': {'model_id': 68},
            'sv': {'model_id': 69},
            'tr': {'model_id': 70},
            'uk': {'model_id': 71},
            'ur': {'model_id': 72},
            'ug': {'model_id': 73},
            'vi': {'model_id': 74}       
        }
    },

    "fasttext": {
        "id": "fasttext",
        "family": "FastText",
        "language_list": ['af', 'sq', 'als', 'am', 'ar', 'an', 'hy', 'as', 'ast', 'az', 'ba', 'eu', 'bar', 'be', 'bn', 'bh', 'bpy', 'bs', 'br', 'bg', 'my', 'ca', 'ceb', 'bcl', 'ce', 'zh', 'cv', 'co', 'hr', 'cs', 'da', 'dv', 'nl', 'pa', 'arz', 'eml', 'en', 'myv', 'eo', 'et', 'hif', 'fi', 'fr', 'gl', 'ka', 'de', 'gom', 'el', 'gu', 'ht', 'he', 'mrj', 'hi', 'hu', 'is', 'io', 'ilo', 'id', 'ia', 'ga', 'it', 'ja', 'jv', 'kn', 'pam', 'kk', 'km', 'ky', 'ko', 'ku', 'ckb', 'la', 'lv', 'li', 'lt', 'lmo', 'nds', 'lb', 'mk', 'mai', 'mg', 'ms', 'ml', 'mt', 'gv', 'mr', 'mzn', 'mhr', 'min', 'xmf', 'mwl', 'mn', 'nah', 'nap', 'ne', 'new', 'frr', 'nso', 'no', 'nn', 'oc', 'or', 'os', 'pfl', 'ps', 'fa', 'pms', 'pl', 'pt', 'qu', 'ro', 'rm', 'ru', 'sah', 'sa', 'sc', 'sco', 'gd', 'sr', 'sh', 'scn', 'sd', 'si', 'sk', 'sl', 'so', 'azb', 'es', 'su', 'sw', 'sv', 'tl', 'tg', 'ta', 'tt', 'te', 'th', 'bo', 'tr', 'tk', 'uk', 'hsb', 'ur', 'ug', 'uz', 'vec', 'vi', 'vo', 'wa', 'war', 'cy', 'vls', 'fy', 'pnb', 'yi', 'yo', 'diq', 'zea'],
        "download_info": {
            'af': 'af',
            'sq': 'sq',
            'als': 'als',
            'am': 'am',
            'ar': 'ar',
            'an': 'an',
            'hy': 'hy',
            'as': 'as',
            'ast': 'ast',
            'az': 'az',
            'ba': 'ba',
            'eu': 'eu',
            'bar': 'bar',
            'be': 'be',
            'bn': 'bn',
            'bh': 'bh',
            'bpy': 'bpy',
            'bs': 'bs',
            'br': 'br',
            'bg': 'bg',
            'my': 'my',
            'ca': 'ca',
            'ceb': 'ceb',
            'bcl': 'bcl',
            'ce': 'ce',
            'zh': 'zh',
            'cv': 'cv',
            'co': 'co',
            'hr': 'hr',
            'cs': 'cs',
            'da': 'da',
            'dv': 'dv',
            'nl': 'nl',
            'pa': 'pa',
            'arz': 'arz',
            'eml': 'eml',
            'en': 'en',
            'myv': 'myv',
            'eo': 'eo',
            'et': 'et',
            'hif': 'hif',
            'fi': 'fi',
            'fr': 'fr',
            'gl': 'gl',
            'ka': 'ka',
            'de': 'de',
            'gom': 'gom',
            'el': 'el',
            'gu': 'gu',
            'ht': 'ht',
            'he': 'he',
            'mrj': 'mrj',
            'hi': 'hi',
            'hu': 'hu',
            'is': 'is',
            'io': 'io',
            'ilo': 'ilo',
            'id': 'id',
            'ia': 'ia',
            'ga': 'ga',
            'it': 'it',
            'ja': 'ja',
            'jv': 'jv',
            'kn': 'kn',
            'pam': 'pam',
            'kk': 'kk',
            'km': 'km',
            'ky': 'ky',
            'ko': 'ko',
            'ku': 'ku',
            'ckb': 'ckb',
            'la': 'la',
            'lv': 'lv',
            'li': 'li',
            'lt': 'lt',
            'lmo': 'lmo',
            'nds': 'nds',
            'lb': 'lb',
            'mk': 'mk',
            'mai': 'mai',
            'mg': 'mg',
            'ms': 'ms',
            'ml': 'ml',
            'mt': 'mt',
            'gv': 'gv',
            'mr': 'mr',
            'mzn': 'mzn',
            'mhr': 'mhr',
            'min': 'min',
            'xmf': 'xmf',
            'mwl': 'mwl',
            'mn': 'mn',
            'nah': 'nah',
            'nap': 'nap',
            'ne': 'ne',
            'new': 'new',
            'frr': 'frr',
            'nso': 'nso',
            'no': 'no',
            'nn': 'nn',
            'oc': 'oc',
            'or': 'or',
            'os': 'os',
            'pfl': 'pfl',
            'ps': 'ps',
            'fa': 'fa',
            'pms': 'pms',
            'pl': 'pl',
            'pt': 'pt',
            'qu': 'qu',
            'ro': 'ro',
            'rm': 'rm',
            'ru': 'ru',
            'sah': 'sah',
            'sa': 'sa',
            'sc': 'sc',
            'sco': 'sco',
            'gd': 'gd',
            'sr': 'sr',
            'sh': 'sh',
            'scn': 'scn',
            'sd': 'sd',
            'si': 'si',
            'sk': 'sk',
            'sl': 'sl',
            'so': 'so',
            'azb': 'azb',
            'es': 'es',
            'su': 'su',
            'sw': 'sw',
            'sv': 'sv',
            'tl': 'tl',
            'tg': 'tg',
            'ta': 'ta',
            'tt': 'tt',
            'te': 'te',
            'th': 'th',
            'bo': 'bo',
            'tr': 'tr',
            'tk': 'tk',
            'uk': 'uk',
            'hsb': 'hsb',
            'ur': 'ur',
            'ug': 'ug',
            'uz': 'uz',
            'vec': 'vec',
            'vi': 'vi',
            'vo': 'vo',
            'wa': 'wa',
            'war': 'war',
            'cy': 'cy',
            'vls': 'vls',
            'fy': 'fy',
            'pnb': 'pnb',
            'yi': 'yi',
            'yo': 'yo',
            'diq': 'diq',
            'zea': 'zea'
        }
    },

    "glove": {
        "id": "glove",
        "family": "Glove",
        "language_list": ["en"],
        "download_info": {
            "en": "http://nlp.stanford.edu/data/glove.42B.300d.zip"
        }
    },

    "elmo": {
        "id": "elmo",
        "family": "ELMo",
        "language_list": ["en"],
        "download_info": {
            "en": "https://tfhub.dev/google/elmo/3?tf-hub-format=compressed"
        }
    },

    "use": {
        "id": "use",
        "family": "USE",
        "language_list": ["en", "multilingual"],
        "download_info": {
            "en": "https://tfhub.dev/google/universal-sentence-encoder/4?tf-hub-format=compressed",
            "multilingual": "https://tfhub.dev/google/universal-sentence-encoder-multilingual/3?tf-hub-format=compressed"
        }
    },


    "bert-base-multilingual-cased": {
        "id": "bert-base-multilingual-cased",
        "family": "Bert",
        "language_list": ["multilingual"],
        "download_info": {
            "multilingual": "bert-base-multilingual-cased"
        }
    },

    "distilbert-base-uncased": {
        "id": "distilbert-base-uncased",
        "family": "DistilBert",
        "language_list": ["en"],
        "download_info": {
            "multilingual": "distilbert-base-uncased"
        }
    }
}

TRANSFORMERS_LIST = ["bert-base-multilingual-cased","distilbert-base-uncased"]

